Finish Base Game Features
cpp-gamedev/pkmn pull request #19
Opened 2021-06-05 17:27 UTC by hentai-chan

Closes issue #17 . The game should now have entered a playable state.

2021-06-05 19:00 UTC, karnkaul requested changes

2021-06-05 19:00 UTC, karnkaul commented on src/main.cpp
> +				sleep(1000);
Just FYI: using `chrono` and `thread` (and `chrono_literals`): `std::this_thread::sleep_for(1000ms)`

2021-06-05 19:00 UTC, karnkaul commented on src/models.hpp
> +	EASY = 1,
By convention, enum values start from 0; is there a good reason this does not? (Adding `INVALID` as `0` and the default might make sense.)

2021-06-05 19:00 UTC, karnkaul commented on src/utils.cpp
> +void slow_print(std::string str, int ms)
`str` should be a const ref / `string_view`

2021-06-05 19:00 UTC, karnkaul commented on src/utils.cpp
> +	for (const char& c : str)
Reference to `char` is actually worse than a copy (8 bytes vs 1, + pointer deref cost if any)

2021-06-05 19:00 UTC, karnkaul commented on src/utils.hpp
> +static constexpr long long str_max{std::numeric_limits<std::streamsize>::max()};
`static` in headers is not a good idea; here you're ok because it's a constant, otherwise it would be UB

2021-06-05 19:00 UTC, karnkaul commented on src/utils.cpp
> +int validate_user_input(std::vector<std::string> table, std::string header)
`table` should be a const ref

2021-06-05 19:00 UTC, karnkaul commented on src/main.cpp
> +				sleep(1000);
Okay so your `utils` function already does that; then have it take a `duration` instead of a raw integer.

2021-06-05 21:18 UTC, hentai-chan commented on src/models.hpp
> +	EASY = 1,
There actually is a good reason for that! It's because of this line:

```cpp
this->level = utils::random_range<int>(max * static_cast<int>(difficulty) - min, max * static_cast<int>(difficulty));
```

I could add `INVALID` as another state at place it at the top, so that I don't have to adjust the formula. The `Pokemon` constructor takes `MODERATE` as a default argument, so it's pretty much impossible that anywhere else I'd have account for the case that `difficulty` is never set, but it does no harm in adding it to the enum so I will probably just do it.

2021-06-05 21:44 UTC, hentai-chan commented on src/utils.cpp
> +int validate_user_input(std::vector<std::string> table, std::string header)
Not quite `const` because I called `lower()` and `upper()` on the `table` and `header`, respectively.  But here I could get away with passing the header already in caps, so it ended up being const-ref anyway.

2021-06-06 00:59 UTC, karnkaul approved these changes

2021-06-06 00:59 UTC, karnkaul commented on src/anim.cpp
> +		utils::sleep(std::chrono::milliseconds{50});
If you use `using namespace std::chrono_literals`, you can use `50ms` here directly.

2021-06-06 14:28 UTC, merged